### ISSUE TITLE
发送的消息到nodejs服务器端解析异常

### ISSUE THREAD

**Issue by littleferry** [Zhang19910325/protoBufferForWeichat#4]
syntax = "proto2";

enum WSType {
    MQInit = 1; // MQ 初始化
    OnlineMsg = 2; // 在线消息
    OfflineMsg = 3; // 离线消息
    OnlineMsgList = 4; // 在线消息列表
    OfflineMsgList = 5; // 离线消息列表
    WSRESULTTYPE = 6;

}

message MQConfig {
    required string host = 1; // MQ服务器域名
    required int32 port = 2; // MQ服务器端口
    required string user = 3; // MQ服务器用户名
    required string pwd = 4; // MQ服务器密码
    required string vhost = 5; // MQ服务器vhost路径
    required string mqExchangeName = 6; // MQ在线分发Exchange名称
    required string mqQueueName = 7; // MQ离线分发Queue名称
    required string mqRoutingKey = 8; // MQ RoutingKey名称
}

message WsMessage {
    required WSType type = 1; // 消息类型
    optional MQConfig mqconfig = 2; // 如果type是MQInit；MQConfig信息放入此字段
}

代码：

    var s = pkgMQInitMsg('1.1.1.1', '1', '1', '1', '1', '1', '1', '1');
    var buffer = s.encode().finish();
    //buffer[2] = 18;

    printDump('encode s: ', s, buffer);
    var deMessage = s.decode(buffer);
    printDump('decode s', deMessage, buffer);

    function pkgMQInitMsg(MqHost, MqPort, MqName, MqPwd, MqExchangeName, MqVHost, MqQueueName, MqRoutingKey) {
  var wsmsg = WsMessage.create();
  var mqconfig = MQConfig.create();
  wsmsg.type = WSType.values.MQInit;
  mqconfig.host = MqHost;
  mqconfig.port = MqPort;
  mqconfig.user = MqName;
  mqconfig.pwd = MqPwd;
  mqconfig.vhost = MqVHost;
  mqconfig.mqExchangeName = MqExchangeName;
  mqconfig.mqQueueName = MqQueueName;
  mqconfig.mqRoutingKey = MqRoutingKey;
  wsmsg.mqconfig = mqconfig;
  return wsmsg;
}

小程序端序列化和反序列化都没有问题：
日志：[8, 1, 19, 29, 10, 7, 49, 46, 49, 46, 49, 46, 49, 16, 1, 26, 1, 49, 34, 1, 49, 42, 1, 49, 50, 1, 49, 58, 1, 49, 66, 1, 49]

但是在服务器端解析的时候异常：
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (/home/nodeproject/netwhiteboard/nodejs/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.doAssertFailure_ (/home/nodeproject/netwhiteboard/nodejs/node_modules/google-protobuf/google-protobuf.js:99:126)
    at Object.goog.asserts.assert (/home/nodeproject/netwhiteboard/nodejs/node_modules/google-protobuf/google-protobuf.js:99:385)
    at jspb.BinaryReader.readMessage (/home/nodeproject/netwhiteboard/nodejs/node_modules/google-protobuf/google-protobuf.js:345:139)
    at Function.proto.com.hengqian.whiteboard.msg.WsMessage.deserializeBinaryFromReader (/home/nodeproject/netwhiteboard/nodejs/whiteboardmsg_pb.js:4290:14)
    at Function.proto.com.hengqian.whiteboard.msg.WsMessage.deserializeBinary (/home/nodeproject/netwhiteboard/nodejs/whiteboardmsg_pb.js:4266:54)
    at InStream.<anonymous> (/home/nodeproject/netwhiteboard/nodejs/websockeMQ.js:22:49)
    at emitNone (events.js:106:13)
    at InStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)

上述日志异常位置是在解析WsMessage的第二个参数mqconfig时出现异常的。

同样的数据，如果我在html5页面生成的消息对象，只有第三位不一样，是18，不是19，如果我在小程序端手动把第三位调成18，服务器端解析没有问题
[8, 1, 19, 29, 10, 7, 49, 46, 49, 46, 49, 46, 49, 16, 1, 26, 1, 49, 34, 1, 49, 42, 1, 49, 50, 1, 49, 58, 1, 49, 66, 1, 49]

帮忙分析一下这个是什么原因？为什么第三位会有差异，这个和google protobuf格式有什么差异？

**Comment by Zhang19910325** [comment]
你好！这个问题我已经收到反馈，并且已经修正。针对你的问题：18对应的二进制是：“00010 010”，序号为2，类型为2（正确）； 19对应的二进制是：“00010 011 ” 序号为2，类型为3（错误），这个是encoder解析错误导致的，已经修正，新版本可以。
